name = "RetentionParameterEstimator"
uuid = "0afdae40-3141-486e-b874-33af99ac38b5"
authors = ["Jan Leppert <jleppert@uni-bonn.de>"]
version = "0.1.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GasChromatographySimulator = "dd82b6e2-56ef-419d-b271-0be268cb65f5"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationCMAEvolutionStrategy = "bd407f91-200f-4536-9381-e4ba712f53f8"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.9, 0.10"
DataFrames = "1.3, 1.4"
GasChromatographySimulator = "0.3"
Interpolations = "0.13, 0.14"
Optimization = "3"
OptimizationBBO = "0.1"
OptimizationCMAEvolutionStrategy = "0.1"
OptimizationOptimJL = "0.1"
OptimizationOptimisers = "0.1"
julia = "1.7, 1.8"
